namespace AzurePrivateEndpointDemo.API.Models;

/// <summary>
/// Represents a chatbot answer returned to the React application.
/// </summary>
public sealed class ChatbotResponseDto
{
    /// <summary>
    /// Creates a chatbot response with its source references.
    /// </summary>
    /// <param name="answer">The answer generated by Azure OpenAI.</param>
    /// <param name="sources">The PDF pages used as context.</param>
    public ChatbotResponseDto(string answer, IReadOnlyList<ChatSourceDto> sources)
    {
        Answer = answer;
        Sources = sources;
    }

    public string Answer { get; }

    public IReadOnlyList<ChatSourceDto> Sources { get; }
}
