name: .NET Build

on:
  push:
    branches:
      - main
    paths:
      - "src/API/**"
      - ".github/workflows/dotnet-build.yml"
  pull_request:
    branches:
      - main
    paths:
      - "src/API/**"
      - ".github/workflows/dotnet-build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build API and Function
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Build
        run: dotnet build AzurePrivateEndpointDemo.slnx --configuration Release
